### ISSUE TITLE
quantity field prevents numbers > package minimum

### ISSUE THREAD

**Issue by unsub** [helgatheviking/woocommerce-mix-and-match-min-max#5]
Although this ultimately shows up as an issue with min-max mini extension, the only fix I can find is to edit the MnM javascript - specifically add-to-cart-mnm.js

Lines 214 to 227 prevent the quantity field from being larger than the minimum container size. I have just commented them out:

```
/*
                        // max can't be higher than the container size
                        if ( container_size > 0 ) {
                            max = Math.min( max, parseFloat( container_size ) );
                        }

                        if ( min >= 0 && parseFloat( $input.val() ) < min ) {
                            $input.val( min );
                        }

                        if ( max > 0 && parseFloat( $input.val() ) > max ) {
                            $input.val( max );
                        }
// */
```

...and re-minified. 
Downside is that the first time I update the main plugin (Mix-n-match products), I'll have to re-edit. I wonder if you would consider adding in an override in some future update? Assuming there will be some. 
In the meantime, brilliant stuff here, and it's totally not a deal-breaker. I'm still using it :)

**Comment by helgatheviking** [comment]
Hey @unsub, thanks for the report. Are you filtering `woocommerce_mnm_quantity_input_min`? That's the only what I've been able to recreate this so far. Can you describe your set up? Or provide a link to where you are seeing this?

**Comment by helgatheviking** [comment]
@franticpsyx what even _is_ [this bit](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/assets/js/add-to-cart-mnm.js#L220-L222) doing? It has almost no effect when the input's minimum is zero, but if you filter `woocommerce_mnm_quantity_input_min` you get some weird things happening.

**Comment by unsub** [comment]
Hi @helgatheviking 
Sorry, yes - environment:
First the browsers, as I'm pretty sure it's a JS thing - Chrome and FF, both latest stable, and Edge, most recent WinX update. All the same. 

Codebase:
The mix&match plugin is the latest version available from my woothemes account, and min-max is just cloned from git this evening. 

Testing Environment is Windows 10, XAMPP (the bitnami branded one, just downloaded 2 weeks ago). Wordpress environment is 4.5.3, using a vanilla install of Storefront theme, as well as tested on 2015 theme. All other plugins deactivated, save WooCommerce itself. I also have same results on Windows 7 machine using wildly out-dated xampp installation, and a custom child-theme of storefront, but not filtering the inputs as you asked about. Started to put together a clone on my Mac, decided I really don't have the patience for it this eve' - but I will if you really want me to... 

But as you can see, I'm 99.9 % certain that it's not an environmental issue. As soon as I comment out those above mentioned lines, it works as (I) expected. I should be able to enter, or use the spinner to select, any number of any item in a mix+match, up to and including the maximum set in min-max mini extension. If I choose the max of one, and then any number of another, the validation (message box, greyed out add-to-cart button, and failing that, the cart validation) should kick in - and does, when I make the JS alteration. 
So we need an override for add-to-cart-mnm.js, or possibly some kind of allowance given in a future version of mnm... which I certainly wouldn't ask for just for one slightly fringe-y case like mine :)

Thanks for the reply. Have a lovely evening!

-Gabriel

**Comment by manospsyx** [comment]
@helgatheviking It prevents an input value lower than `min` by auto-resetting it to the defined minimum.

**Comment by helgatheviking** [comment]
@franticpsyx thanks! I thought that was the problem line, but now I'm pretty sure it's [here](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/assets/js/add-to-cart-mnm.js#L217). The min/max quantities are set to save the minimum as MNM's default container size. This then passes the min size as the container size data attribute which is picked up by the script as the [`container_size`](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/assets/js/add-to-cart-mnm.js#L191). Looking back at [line 217](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/assets/js/add-to-cart-mnm.js#L217) it's pulling the minimum of the two numbers: input's max and the container's max (which is incorrectly being calculated from the container's minimum) and thus the input can be limited to the container's min size. I hope you followed that b/c it sounds like a mess to me.

My thought is that the mini extension needs to filter the [`get_container_size()`](https://github.com/woothemes/woocommerce-mix-and-match-products/blob/master/includes/class-wc-product-mix-and-match.php#L106) to be 0 if the min does not equal the max. Having a 0 value for the container size will disable the line 217 check (like it would be if the container size was unlimited) and the min/max extension should work properly while not breaking the core plugin. :fireworks: 

@unsub please try [this branch](https://github.com/helgatheviking/woocommerce-mix-and-match-min-max/tree/remove-container-size-attr). It's going to need some testing to make sure that the cart validation still works as expected.

**Comment by unsub** [comment]
@helgatheviking Seems to work brilliantly. Did a full reinstall of everything, using this branch, and it functions exactly as I hoped. Thanks :)

**Comment by manospsyx** [comment]
@helgatheviking Using '0' as an equivalent for 'unlimited' did have some complications, made things unnecessarily complex, I think. Would have been wiser to use an empty string instead, I think. Not sure if it would have made things easier in this case.

If we ever decide to "merge" this mini-extension into the main plugin, we could migrate the meta and re-write the code to make things easier to debug.

**Comment by helgatheviking** [comment]
@franticpsyx do you remember what those complications were? I thought that 0 was equivalent to unlimited. If it would be better I think the same thing might be achieved here by returning a null string instead of zero.

**Comment by manospsyx** [comment]
I think I had a couple moments of head-scratching when looking at the `js` (both for MnM and the mini-extension), but nothing that couldn't be understood in the end. The biggest issue is the UX - a "Container Size = 0" setting translating into unlimited is a bit less obvious than, say, leaving the field empty. Also forcing a min qty = 1 when the container size is unlimited was something that couldn't be inferred from a "Container Size = 0" setting as well (although it makes sense if you think about it a bit). 

Perhaps if "unlimited" would have been a feature of the Min/Max mini-extension, then things would be a bit more straightforward from the beginning since the unlimited max qty could have been implemented as a an empty string or `null` value, and all the "unlimited" logic would be in one place.

Not that it matters too much... I wish we had some data about active MnM and mini-extension installs, would help make more informed decisions.

**Comment by helgatheviking** [comment]
> Perhaps if "unlimited" would have been a feature of the Min/Max mini-extension

ugh, 20/20 hindsight. that does make more sense. 

> I wish we had some data about active MnM and mini-extension installs, would help make more informed decisions

that'd be sweeeet. 

I think I'm going to leave the zero for no, it seems to work.

**Comment by helgatheviking** [comment]
@unsub @franticpsyx we didn't actually need to make any changes to MNM for this right? My git says I have something that needs staging but I'm mostly sure I can ignore it.

**Comment by unsub** [comment]
Hi there,
Funny this timing - I've been away for most of a month, just started work again, and about an hour ago I noticed that the minimum for a bundle no longer works. Whatever is in there is ignored, and the alert (blue) always says "select between 1 and (whatever the max is)".
I'm sorry :( 
My working version had used a hacked js file in MNM and v.1.0.1 of min-max to fix the maximum allowable. Now with min-max 1.0.2 and fresh install of MNM, I get the minimum being ignored. I think somehow I missed this during my final test, or a woo-update of some kind?

**Comment by unsub** [comment]
just threw up a test for you - it's on an old domain, and it's only got one product in there, but it will show what I mean:
http://studio440.ca/dvlpmnt
the MNM product is the "3 for 4" thing. You'll see.
I've got the minimum set to 3 and the maximum set to 4, but it ignores the minimum.

**Comment by helgatheviking** [comment]
Well damn. Looks like filtering the container size = 0 wasn't such a good idea because the container size is also the minimum. Since the minimum is 0 the alert will always set the minimum as 1. Gonna have to give that a think. 

What if you remove the [filter](https://github.com/helgatheviking/woocommerce-mix-and-match-min-max/blob/master/woocommerce-mix-and-match-min-max-quantities.php#L90) I added?

**Comment by helgatheviking** [comment]
Nope, that doesn't do it. Sunday at 10pm is not really the best time to start this, but I'll look at it again in the morning.

**Comment by helgatheviking** [comment]
Can you try the latest version of [this branch](https://github.com/helgatheviking/woocommerce-mix-and-match-min-max/blob/remove-container-size-attr/woocommerce-mix-and-match-min-max-quantities.php)?

**Comment by unsub** [comment]
Well, that did the trick! 
Works great on the test site I put up, and also one of my home computers (xampp) so I would say that's sorted. 
And @ 10 on a Sunday night, too! :D Nice.

**Comment by helgatheviking** [comment]
Well not too surprisingly sunday night code is untested, and so when I tested containers with a fixed quantity (aka min=max) it broke things. I think I have a fix for that coming in a minute or two.

**Comment by helgatheviking** [comment]
@unsub version 1.0.3 should do the trick.
